### ISSUE TITLE
The hour displayes in main page is not correct

### ISSUE THREAD

**Issue by AlbertPG** [ASW-Grup11A/ASW_Grup11A#8]
The contribution creation hour that is displayed in the main page should be calculated.

**Comment by AlbertPG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Main page logged interface](https://trello.com/c/RleGddbY/2-main-page-logged-interface)

**Comment by marclll** [comment]
Solved

**Comment by marclll** [comment]
Solved by using the library humanize
